Models/Empleado.cs
namespace EFCRUD8.Models
{
    public class Empleado
    {
        public int IdEmpleado { get; set; }

        public string Nombre { get; set; }

        public string Apellido { get; set; }

        public string Correo { get; set; }

        public DateOnly FechaContrato { get; set; }

        public bool Activo { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace EFCRUD8.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EmpleadoController.cs
using Microsoft.AspNetCore.Mvc;

using EFCRUD8.Data;
using EFCRUD8.Models;
using Microsoft.EntityFrameworkCore;

namespace EFCRUD8.Controllers
{
    public class EmpleadoController : Controller
    {
        private readonly AppDBContext _appDBContext;

        public EmpleadoController(AppDBContext appDBContext)
        {
            _appDBContext = appDBContext;
        }

        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            List<Empleado> lista = await _appDBContext.Empleados.ToListAsync();
            return View(lista);
        }

        [HttpGet]
        public IActionResult Nuevo()
        {
            
            return View();
        }

        [HttpPost]
        public async  Task<IActionResult> Nuevo(Empleado empleado)
        {
            await _appDBContext.Empleados.AddAsync(empleado);
            await _appDBContext.SaveChangesAsync();
            return RedirectToAction(nameof(Lista));
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            Empleado empleado = await _appDBContext.Empleados.FirstAsync(e => e.IdEmpleado == id);
            return View(empleado);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(Empleado empleado)
        {
            _appDBContext.Empleados.Update(empleado);
            await _appDBContext.SaveChangesAsync();
            return RedirectToAction(nameof(Lista));
        }

        [HttpGet]
        public async Task<IActionResult> Eliminar(int id)
        {
            Empleado empleado = await _appDBContext.Empleados.FirstAsync(e => e.IdEmpleado == id);

            _appDBContext.Empleados.Remove(empleado);
            await _appDBContext.SaveChangesAsync();
            return RedirectToAction(nameof(Lista));
        }
    }
}

Controllers/HomeController.cs
using EFCRUD8.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EFCRUD8.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Empleado/Editar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@model EFCRUD8.Models.Empleado;

<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h2>Editar Empleado</h2>

        <form asp-controller="Empleado" asp-action="Editar" method="post">
            <input asp-for="IdEmpleado" type="hidden" />
            <div class="mb-3">
                <label>Nombre</label>
                <input class="form-control" asp-for="Nombre" type="text" />
            </div>

            <div class="mb-3">
                <label>Apellido</label>
                <input class="form-control" asp-for="Apellido" type="text" />
            </div>

            <div class="mb-3">
                <label>Correo</label>
                <input class="form-control" asp-for="Correo" type="text" />
            </div>

            <div class="mb-3">
                <label>Fecha Contrato</label>
                <input class="form-control" asp-for="FechaContrato" type="date" />
            </div>

            <div class="mb-3">
                <input class="form-check-input" asp-for="Activo" type="checkbox" id="chkActivo" />
                <label class="form-check-label" for="chkActivo">Activo</label>
            </div>

            <div class="mb-3">
                <button class="btn btn-primary" type="submit">Guardar</button>
                <a asp-controller="Empleado" asp-action="Lista" class="btn btn-warning">Volver</a>
            </div>
        </form>

    </div>
</div>

Views/Empleado/Lista.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model List<EFCRUD8.Models.Empleado>;
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h2>Lista empleado</h2>
        <a asp-controller="Empleado" asp-action="Nuevo" class="btn btn-success mb-3">Nuevo</a>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Correo</th>
                    <th>Fecha contratado</th>
                    <th>Activo</th>
                    <th></th>
                </tr>
            </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.IdEmpleado</td>
                    <td>@item.Nombre</td>
                    <td>@item.Apellido</td>
                    <td>@item.Correo</td>
                    <td>@item.FechaContrato.ToString("dd/MMd/yyyy")</td>
                    <td>@(item.Activo ? "SI": "NO")</td>
                    <td>
                        <a
                            asp-controller="Empleado"
                            asp-action="Editar"
                            asp-route-id="@item.IdEmpleado"
                            class="btn btn-primary">
                            Editar
                        </a>

                        <a asp-controller="Empleado"
                            asp-action="Eliminar"
                            asp-route-id="@item.IdEmpleado"
                            onclick="return confirmar()"
                            class="btn btn-danger">
                            Eliminar
                        </a>
                    </td>
                </tr>
            }
        </tbody>
        </table>
    </div>
</div>

@section Scripts{
    <script>
        function confirmar() {
            return confirm("Estas seguro de eliminar el empleado")
        }
    </script>
}

Views/Empleado/Nuevo.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@model EFCRUD8.Models.Empleado;

<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h2>Nuevo Empleado</h2>
        
    <form asp-controller="Empleado" asp-action="Nuevo" method="post">
        <div class="mb-3">
            <label>Nombre</label>
            <input class="form-control" asp-for="Nombre" type="text" />
        </div>

        <div class="mb-3">
                <label>Apellido</label>
                <input class="form-control" asp-for="Apellido" type="text" />
        </div>

        <div class="mb-3">
            <label>Correo</label>
            <input class="form-control" asp-for="Correo" type="text" />
        </div>

        <div class="mb-3">
            <label>Fecha Contrato</label>
            <input class="form-control" asp-for="FechaContrato" type="date" />
        </div>
        
        <div class="mb-3">
            <input class="form-check-input" asp-for="Activo" type="checkbox" id="chkActivo" />
            <label class="form-check-label" for="chkActivo">Activo</label>
        </div>

        <div class="mb-3">
            <button class="btn btn-primary" type="submit">Guardar</button>
            <a asp-controller="Empleado" asp-action="Lista" class="btn btn-warning">Volver</a>
        </div>
    </form>

    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EFCRUD8</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EFCRUD8.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EFCRUD8</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EFCRUD8 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>